# markdownlint-cli2 configuration
# https://github.com/DavidAnson/markdownlint-cli2

# Ignore patterns (node_modules should be excluded)
ignores:
  - "**/node_modules/**"
  - "**/*.yaml"
  - "**/*.yml"
  - ".github/templates/**"
