"""Tests for dependency synchronization scripts.

These tests ensure that:
1. Tool versions in pyproject.toml align with CI pin file
2. Test dependencies are declared in pyproject.toml
3. Lock files can be regenerated consistently
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"
PYPROJECT_FILE = REPO_ROOT / "pyproject.toml"
PIN_FILE = REPO_ROOT / ".github" / "workflows" / "autofix-versions.env"


class TestSyncToolVersions:
    """Tests for sync_tool_versions.py."""

    def test_pin_file_exists(self) -> None:
        """Pin file must exist for version synchronization."""
        assert PIN_FILE.exists(), f"Pin file not found: {PIN_FILE}"

    def test_pyproject_exists(self) -> None:
        """pyproject.toml must exist."""
        assert PYPROJECT_FILE.exists(), f"pyproject.toml not found: {PYPROJECT_FILE}"

    def test_sync_script_exists(self) -> None:
        """Sync script must exist."""
        script = SCRIPTS_DIR / "sync_tool_versions.py"
        assert script.exists(), f"Sync script not found: {script}"

    def test_versions_aligned(self) -> None:
        """Tool versions should be aligned between pin file and pyproject.toml."""
        script = SCRIPTS_DIR / "sync_tool_versions.py"
        result = subprocess.run(
            [sys.executable, str(script), "--check"],
            capture_output=True,
            text=True,
            cwd=REPO_ROOT,
        )
        # Allow warnings but check for success
        assert result.returncode == 0 or "aligned" in result.stdout.lower(), (
            f"Tool versions are misaligned.\n"
            f"stdout: {result.stdout}\n"
            f"stderr: {result.stderr}\n"
            f"Run: python scripts/sync_tool_versions.py --apply"
        )


class TestSyncTestDependencies:
    """Tests for sync_test_dependencies.py."""

    def test_sync_script_exists(self) -> None:
        """Sync script must exist."""
        script = SCRIPTS_DIR / "sync_test_dependencies.py"
        assert script.exists(), f"Sync script not found: {script}"

    def test_no_missing_dependencies(self) -> None:
        """All test imports should be declared in pyproject.toml."""
        script = SCRIPTS_DIR / "sync_test_dependencies.py"
        result = subprocess.run(
            [sys.executable, str(script), "--verify"],
            capture_output=True,
            text=True,
            cwd=REPO_ROOT,
        )
        assert result.returncode == 0, (
            f"Missing test dependencies detected.\n"
            f"stdout: {result.stdout}\n"
            f"stderr: {result.stderr}\n"
            f"Run: python scripts/sync_test_dependencies.py --fix"
        )


class TestLockFiles:
    """Tests for lockfile consistency."""

    def test_requirements_lock_exists(self) -> None:
        """requirements.lock must exist."""
        lock_file = REPO_ROOT / "requirements.lock"
        assert lock_file.exists(), (
            "requirements.lock not found. "
            "Generate with: uv pip compile --upgrade pyproject.toml "
            "--extra dev --extra ocr --extra orchestration -o requirements.lock"
        )

    def test_lock_file_header(self) -> None:
        """requirements.lock should indicate how it was generated."""
        lock_file = REPO_ROOT / "requirements.lock"
        if lock_file.exists():
            content = lock_file.read_text(encoding="utf-8")
            has_header = "uv pip compile" in content or "autogenerated by uv pip compile" in content
            assert has_header, (
                "requirements.lock is missing a generation header. "
                "Regenerate with: uv pip compile --upgrade pyproject.toml "
                "--extra dev --extra ocr --extra orchestration -o requirements.lock"
            )


class TestPinFileFormat:
    """Tests for pin file format."""

    def test_pin_file_format(self) -> None:
        """Pin file should have valid format."""
        content = PIN_FILE.read_text(encoding="utf-8")

        required_vars = [
            "RUFF_VERSION",
            "MYPY_VERSION",
            "PYTEST_VERSION",
        ]

        for var in required_vars:
            assert f"{var}=" in content, f"Pin file missing {var}"

    def test_pin_file_versions_are_valid(self) -> None:
        """Pin file versions should be valid semver-like."""
        import re

        content = PIN_FILE.read_text(encoding="utf-8")
        version_pattern = re.compile(r"^\d+\.\d+(\.\d+)?$")

        for line in content.splitlines():
            if "=" in line and not line.strip().startswith("#"):
                key, value = line.split("=", 1)
                value = value.strip()
                if value:  # Skip empty values
                    assert version_pattern.match(value), (
                        f"Invalid version format for {key}: '{value}'. "
                        f"Expected format: X.Y or X.Y.Z"
                    )
